#!/bin/bash
for file in "$1"/*.txt; do
	while read line; do
		name=$(echo "$line" | cut -d: -f1)
		age=$(echo "$line" | cut -d: -f2)
		email=$(echo "$line" | cut -d: -f3)
		echo "Имя: $name, Возраст: $age, Email: $email"
	done < "$file"
Done
